/*!
 *
 * Bryntum Scheduler Pro 5.3.7
 *
 * Copyright(c) 2023 Bryntum AB
 * https://bryntum.com/contact
 * https://bryntum.com/license
 *
 */
var u=Object.defineProperty;var n=(s,e,t)=>e in s?u(s,e,{enumerable:!0,configurable:!0,writable:!0,value:t}):s[e]=t;var i=(s,e,t)=>(n(s,typeof e!="symbol"?e+"":e,t),t);import{Container as c,Rotatable as g}from"./Editor.js";const o=class extends c.mixin(g){onChildAdd(e){super.onChildAdd(e),e.ion({click:"resetValueCache",toggle:"onItemToggle",thisObj:this,prio:1e4})}onChildRemove(e){e.un({toggle:"resetValueCache",click:"resetValueCache",thisObj:this}),super.onChildRemove(e)}onItemToggle(e){const t=this;t.resetValueCache(),!t.isSettingValue&&(!t.toggleGroup||e.pressed)&&t.triggerFieldChange({value:t.value,userAction:!0,event:e})}resetValueCache(){this._value=null}createWidget(e){const t=this;return t.constructor.resolveType(e.type||"button").isButton&&(t.color&&!e.color&&(e.color=t.color),t.toggleGroup&&!e.toggleGroup&&(typeof t.toggleGroup=="boolean"&&(t.toggleGroup=o.generateId("toggleGroup")),e.toggleGroup=t.toggleGroup)),t.columns&&(e.width=`${100/t.columns}%`),e=super.createWidget(e),t.relayEvents(e,["click","action","toggle"]),e}updateRotate(e){this.eachWidget(t=>{t.rotate!==!1&&(t.rotate=e)})}get value(){if(!this._value){const e=[];this.items.forEach(t=>{t.pressed&&t.value!==void 0&&e.push(t.value)}),this._value=e.join(this.valueSeparator)}return this._value}set value(e){const t=this,r=t.value;Array.isArray(e)||(e==null?e=[]:typeof e=="string"?e=e.split(t.valueSeparator):e=[e]),t._value=e.join(t.valueSeparator),t.isSettingValue=!0,t.items.forEach(a=>{a.value!==void 0&&(a.pressed=e.includes(a.value))}),t.isSettingValue=!1,!t.isConfiguring&&r!==t.value&&t.triggerFieldChange({value:t.value,userAction:!1})}updateDisabled(e){this.items.forEach(t=>t.disabled=e||!t.ignoreParentReadOnly&&this.readOnly)}updateReadOnly(e){super.updateReadOnly(e),this.updateDisabled(this.disabled)}get widgetClassList(){const e=super.widgetClassList;return this.columns&&e.push("b-columned"),e}};let l=o;i(l,"$name","ButtonGroup"),i(l,"type","buttongroup"),i(l,"configurable",{defaultType:"button",cls:null,items:null,color:null,toggleGroup:null,valueSeparator:",",columns:null,hideWhenEmpty:!0,defaultBindProperty:"value"}),l.initClass(),l._$name="ButtonGroup";export{l as ButtonGroup};
//# sourceMappingURL=ButtonGroup.js.map
