/* ---------------------------------------------------------------------*
*                             Acumatica Inc.                            *

*              Copyright (c) 2005-2024 All rights reserved.             *

*                                                                       *

*                                                                       *

* This file and its contents are protected by United States and         *

* International copyright laws.  Unauthorized reproduction and/or       *

* distribution of all or any portion of the code contained herein       *

* is strictly prohibited and will result in severe civil and criminal   *

* penalties.  Any violations of this copyright will be prosecuted       *

* to the fullest extent possible under law.                             *

*                                                                       *

* UNDER NO CIRCUMSTANCES MAY THE SOURCE CODE BE USED IN WHOLE OR IN     *

* PART, AS THE BASIS FOR CREATING A PRODUCT THAT PROVIDES THE SAME, OR  *

* SUBSTANTIALLY THE SAME, FUNCTIONALITY AS ANY ACUMATICA PRODUCT.       *

*                                                                       *

* THIS COPYRIGHT NOTICE MAY NOT BE REMOVED FROM THIS FILE.              *

* --------------------------------------------------------------------- */

using System;

namespace PX.Objects.AR.CCPaymentProcessing.Common
{
	/// <summary>A supplementary class to receive specific transaction data from the Acumatica ERP core.</summary>
	public class TranProcessingInput
	{
		/// <summary>The internal unique transaction identifier.</summary>
		public int TranID;
		/// <summary>The internal Acumatica ERP unique credit card identifier.</summary>
		/// <remarks>Information on credit cards might be obtained by using the <tt>ReadData</tt> method of the <see cref="ICreditCardDataReader" /> interface.</remarks>
		public int? PMInstanceID;
		/// <summary>The unique customer identifier.</summary>
		public string CustomerCD;
		/// <summary>The type of the payment document.</summary>
		/// <remarks>Document information might be obtained by using <see cref="IDocDetailsDataReader" /> interface.</remarks>
		public string DocType;
		/// <summary>The reference number of the payment document.</summary>
		/// <remarks>Document information might be obtained by using <see cref="IDocDetailsDataReader" /> interface.</remarks>
		public string DocRefNbr;
		/// <summary>The original reference number of the document.</summary>
		public string OrigRefNbr;
		/// <summary>The ISO code of the transaction currency.</summary>
		public string CuryID;
		/// <summary>The amount of transaction.</summary>
		public decimal Amount;
		/// <summary>A field that indicates (if set to <tt>true</tt>) that verification of the CVV is required.</summary>
		public bool VerifyCVV;
		/// <summary>A unique identifier of transaction generated by Acumatica ERP. </summary>
		public Guid? TranUID;
		/// <summary>Means of payment of the transaction.</summary>
		public string MeansOfPayment;
		/// <summary>Amount before tax.</summary>
		public decimal? SubtotalAmount;
		/// <summary>Total tax amount.</summary>
		public decimal? Tax;
		/// <summary>POS Terminal ID</summary>
		public string POSTerminalID;
	}
}
